### ISSUE TITLE
Show track downward in TrackScheme Hierarchy View leads to crash

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#222]
# Reproduction

1. Start Fiji
2. Plugins > Mastodon
3. open Mastodon project > open grapher-bug.mastodon (download: https://cloudstore.zih.tu-dresden.de/index.php/s/XgbnqRDgb9jLXLb)
4. Window > New TrackScheme Hierarchy
5. Select a branch
6. View > Show Track Downward > Program crashes

# Expected behaviour:

After step 6. "Show Track Downward", the TrackScheme Hierarchy view should zoom to the sub-tree of the selected branch

# File for testing:

https://cloudstore.zih.tu-dresden.de/index.php/s/XgbnqRDgb9jLXLb

# StackTrace:

![grafik](https://user-images.githubusercontent.com/10515534/208113255-0efd6315-bd9c-4ce0-9f92-f8f45fff36ed.png)

# UI interaction:
![GIF 16 12 2022 14-52-26](https://user-images.githubusercontent.com/10515534/208113316-4aae847e-5b85-4432-b575-8ce774dceac9.gif)

**Comment by tpietzsch** [comment]
The exception is from the "Rebuild spatial indices" thread which runs continuously in the background.
Do you think this is because something in the foreground (caused by Show Track Downward) eats up all the memory? And hence the location where the OOM finally occurs is rather arbitrary? Or is this more closely related?

**Comment by maarzt** [comment]
> @tpietzsch: Do you think this is because something in the foreground (caused by Show Track Downward) eats up all the memory? And hence the location where the OOM finally occurs is rather arbitrary? Or is this more closely related?

 I think you are right. This bug is not related to the spatial index. It just so happened that the spatial index triggered the OutOfBoundsException.

There might be a loop in the graph. The "Show Track Downward" operation does a depth first search to find the roots of the selected sub trees. This depth first search has no detection for loops and it therefor doesn't terminate. I will fix it.

**Comment by stefanhahmann** [comment]
Resolve with #229
